/**
 * Shared Slack app helpers for SchemaLens.
 *
 * Requires environment variables (set in Vercel dashboard):
 *   SLACK_CLIENT_ID     - Slack app client ID
 *   SLACK_CLIENT_SECRET - Slack app client secret
 *   SLACK_SIGNING_SECRET- Slack app signing secret for request verification
 *   SLACK_BOT_TOKEN     - OAuth bot user token (xoxb-...)
 */

const crypto = require('crypto');
const {
  parseSQL,
  diffSchemas,
  detectBreakingChanges,
  calculateRiskScore,
  generateMigration
} = require('./engine');

const BASE_URL = process.env.VERCEL_URL ? `https://${process.env.VERCEL_URL}` : 'https://schemalens.tech';

function getEnv(name) {
  return process.env[name] || '';
}

function isConfigured() {
  return !!(getEnv('SLACK_CLIENT_ID') && getEnv('SLACK_CLIENT_SECRET') && getEnv('SLACK_SIGNING_SECRET'));
}

function isBotConfigured() {
  return !!getEnv('SLACK_BOT_TOKEN');
}

/**
 * Verify a Slack request signature per Slack docs.
 * https://api.slack.com/authentication/verifying-requests-from-slack
 */
function verifySlackRequest(req, rawBody) {
  const signingSecret = getEnv('SLACK_SIGNING_SECRET');
  if (!signingSecret) return false;

  const signature = req.headers['x-slack-signature'] || '';
  const timestamp = req.headers['x-slack-request-timestamp'] || '';
  const ts = parseInt(timestamp, 10);
  if (isNaN(ts)) return false;
  // Reject requests older than 5 minutes to prevent replay attacks
  if (Math.abs(Date.now() / 1000 - ts) > 300) return false;

  const baseString = `v0:${timestamp}:${rawBody}`;
  const expected = 'v0=' + crypto.createHmac('sha256', signingSecret).update(baseString).digest('hex');
  return crypto.timingSafeEqual(Buffer.from(signature, 'utf8'), Buffer.from(expected, 'utf8'));
}

function truncate(str, len) {
  if (!str) return '';
  return str.length > len ? str.slice(0, len - 1) + '…' : str;
}

function formatDiffSlackMessage({ oldSchema, newSchema, dialect = 'postgres', source = 'Slash command' }) {
  const oldParsed = parseSQL(oldSchema || '', dialect);
  const newParsed = parseSQL(newSchema || '', dialect);
  const diff = diffSchemas(oldParsed, newParsed);
  const breaking = detectBreakingChanges(diff);
  const risk = calculateRiskScore(diff);
  const migration = generateMigration(diff, dialect);

  const added = diff.tablesAdded?.length || 0;
  const removed = diff.tablesRemoved?.length || 0;
  const modified = diff.tablesModified?.length || 0;
  const breakingCount = breaking.length;

  let emoji = '🟢';
  if (breakingCount > 0) emoji = '🔴';
  else if (added > 0 || removed > 0 || modified > 0) emoji = '🟡';

  const summaryParts = [];
  if (added) summaryParts.push(`${added} added`);
  if (removed) summaryParts.push(`${removed} removed`);
  if (modified) summaryParts.push(`${modified} modified`);
  if (!summaryParts.length) summaryParts.push('No changes');

  const blocks = [
    {
      type: 'header',
      text: { type: 'plain_text', text: `${emoji} SchemaLens Diff Report`, emoji: true }
    },
    {
      type: 'section',
      fields: [
        { type: 'mrkdwn', text: `*Source:*\n${source}` },
        { type: 'mrkdwn', text: `*Dialect:*\n${dialect}` },
        { type: 'mrkdwn', text: `*Changes:*\n${summaryParts.join(', ')}` },
        { type: 'mrkdwn', text: `*Risk:*\n${risk.icon || ''} ${risk.label || 'Low'} (${risk.score || 0})` }
      ]
    }
  ];

  if (breakingCount > 0) {
    const items = breaking.slice(0, 8).map(b => {
      const icon = b.severity === 'critical' ? '🔴' : '⚠️';
      return `${icon} ${truncate(b.details, 250)}`;
    });
    blocks.push({
      type: 'section',
      text: { type: 'mrkdwn', text: `*Breaking Changes (${breakingCount}):*\n${items.join('\n')}` }
    });
  }

  if (migration) {
    blocks.push({
      type: 'section',
      text: { type: 'mrkdwn', text: `*Migration SQL:*\n\`\`\`sql\n${truncate(migration, 2800)}\n\`\`\`` }
    });
  }

  blocks.push({
    type: 'actions',
    elements: [
      {
        type: 'button',
        text: { type: 'plain_text', text: 'Open in SchemaLens', emoji: true },
        url: `${BASE_URL}/app.html`,
        action_id: 'open_app'
      }
    ]
  });

  blocks.push({
    type: 'context',
    elements: [
      { type: 'mrkdwn', text: `Generated by <${BASE_URL}|SchemaLens>` }
    ]
  });

  return { blocks, text: `SchemaLens diff: ${summaryParts.join(', ')} — ${breakingCount} breaking issue${breakingCount === 1 ? '' : 's'}` };
}

async function sendSlackMessage(channel, message) {
  const token = getEnv('SLACK_BOT_TOKEN');
  if (!token) throw new Error('SLACK_BOT_TOKEN not configured');

  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), 10000);

  try {
    const res = await fetch('https://slack.com/api/chat.postMessage', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${token}`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({ channel, ...message }),
      signal: controller.signal
    });
    clearTimeout(timeout);
    const data = await res.json();
    if (!data.ok) throw new Error(data.error || 'Slack API error');
    return data;
  } catch (err) {
    clearTimeout(timeout);
    throw err;
  }
}

async function exchangeSlackCode(code, redirectUri) {
  const clientId = getEnv('SLACK_CLIENT_ID');
  const clientSecret = getEnv('SLACK_CLIENT_SECRET');

  const params = new URLSearchParams({
    client_id: clientId,
    client_secret: clientSecret,
    code,
    redirect_uri: redirectUri
  });

  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), 10000);

  try {
    const res = await fetch('https://slack.com/api/oauth.v2.access', {
      method: 'POST',
      headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
      body: params.toString(),
      signal: controller.signal
    });
    clearTimeout(timeout);
    return await res.json();
  } catch (err) {
    clearTimeout(timeout);
    throw err;
  }
}

module.exports = {
  BASE_URL,
  getEnv,
  isConfigured,
  isBotConfigured,
  verifySlackRequest,
  formatDiffSlackMessage,
  sendSlackMessage,
  exchangeSlackCode
};
