/**
 * SchemaLens FREE Diff API
 * POST /api/free-diff
 *
 * No license key required. Returns the full semantic diff and generated migration
 * SQL, just like the web UI. Perfect for CI/CD pipelines, open-source projects,
 * and quick checks.
 *
 * Body:
 *   schemaA     string  required  Old schema SQL
 *   schemaB     string  required  New schema SQL
 *   dialect     string  optional  postgres | mysql | sqlite | mssql | oracle (default: postgres)
 *   format      string  optional  json | markdown (default: json)
 *
 * Response (json):
 *   summary           object   Counts of changes
 *   riskScore         object   Risk score (0-100), label, icon
 *   breakingChanges   array    All detected breaking changes
 *   migration         string   Full generated migration SQL
 *   rollback          string   Full generated rollback SQL
 *   teamUpsell        object   Link to Team features (drift alerts, shared workspace)
 *
 * Response (markdown):
 *   markdown          string   Full markdown report with migration SQL
 */

const {
  parseSQL,
  diffSchemas,
  detectBreakingChanges,
  calculateRiskScore,
  generateMigration,
  generateRollbackMigration
} = require('../lib/engine');

// Stricter rate limit for free tier
const rateLimitMap = new Map();
const RATE_LIMIT_WINDOW_MS = 60 * 1000;
const RATE_LIMIT_MAX_REQUESTS = 15;

function isRateLimited(ip) {
  const now = Date.now();
  const entry = rateLimitMap.get(ip);
  if (!entry) {
    rateLimitMap.set(ip, { count: 1, resetAt: now + RATE_LIMIT_WINDOW_MS });
    return false;
  }
  if (now > entry.resetAt) {
    rateLimitMap.set(ip, { count: 1, resetAt: now + RATE_LIMIT_WINDOW_MS });
    return false;
  }
  entry.count++;
  if (entry.count > RATE_LIMIT_MAX_REQUESTS) return true;
  return false;
}

setInterval(() => {
  const now = Date.now();
  for (const [ip, entry] of rateLimitMap) {
    if (now > entry.resetAt + RATE_LIMIT_WINDOW_MS) rateLimitMap.delete(ip);
  }
}, 5 * 60 * 1000);

module.exports = (req, res) => {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');

  if (req.method === 'OPTIONS') return res.status(200).end();

  const clientIp = req.headers['x-forwarded-for']?.split(',')[0]?.trim() || req.socket?.remoteAddress || 'unknown';
  if (isRateLimited(clientIp)) {
    return res.status(429).json({
      error: 'Rate limit exceeded. Maximum 15 requests per minute on the free tier. Upgrade to SchemaLens Team for unlimited CI/CD diff checks.',
      teamUpsell: 'https://schemalens.tech/team-buy.html'
    });
  }

  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed. Use POST.' });
  }

  const { schemaA, schemaB, dialect = 'postgres', format = 'json' } = req.body || {};

  if (typeof schemaA !== 'string' || typeof schemaB !== 'string') {
    return res.status(400).json({ error: 'schemaA and schemaB are required string fields.' });
  }

  const validDialects = ['postgres', 'mysql', 'sqlite', 'mssql', 'oracle'];
  if (!validDialects.includes(dialect)) {
    return res.status(400).json({ error: `Invalid dialect. Must be one of: ${validDialects.join(', ')}` });
  }

  const validFormats = ['json', 'markdown'];
  if (!validFormats.includes(format)) {
    return res.status(400).json({ error: `Invalid format. Must be one of: ${validFormats.join(', ')}` });
  }

  try {
    const oldSchema = parseSQL(schemaA, dialect);
    const newSchema = parseSQL(schemaB, dialect);
    const diff = diffSchemas(oldSchema, newSchema);
    const breakingChanges = detectBreakingChanges(diff);
    const riskScore = calculateRiskScore(diff);
    const migration = generateMigration(diff, dialect);
    const rollback = generateRollbackMigration(diff, dialect);

    if (format === 'markdown') {
      const lines = migration.split('\n').filter(l => l.trim()).length;
      const md = [
        '## Schema Diff Summary',
        '',
        `**Dialect:** ${dialect}`,
        `**Risk Score:** ${riskScore.score}/100 (${riskScore.label})`,
        '',
        '| Change Type | Count |',
        '|-------------|-------|',
        `| Tables Added | ${diff.tablesAdded.length} |`,
        `| Tables Removed | ${diff.tablesRemoved.length} |`,
        `| Tables Modified | ${diff.tablesModified.length} |`,
        `| Breaking Changes | ${breakingChanges.length} |`,
        '',
        '### Generated Migration',
        '```sql',
        migration || '-- No migration needed',
        '```',
        '',
        lines > 0 ? `*${lines} migration line(s) generated by [SchemaLens Free Diff API](https://schemalens.tech/api-guide.html)*` : '*No migration needed.*',
        '',
        '> 💡 **Running this in production?** Add [SchemaLens Team](https://schemalens.tech/team-buy.html) for drift alerts, a shared workspace, and Slack/Teams notifications.',
        ''
      ].join('\n');
      return res.status(200).json({ markdown: md });
    }

    return res.status(200).json({
      summary: {
        tablesAdded: diff.tablesAdded.length,
        tablesRemoved: diff.tablesRemoved.length,
        tablesRenamed: diff.tablesRenamed?.length || 0,
        tablesModified: diff.tablesModified.length,
        enumsAdded: diff.enumsAdded?.length || 0,
        enumsRemoved: diff.enumsRemoved?.length || 0,
        viewsAdded: diff.viewsAdded?.length || 0,
        viewsRemoved: diff.viewsRemoved?.length || 0,
        viewsModified: diff.viewsModified?.length || 0,
        triggersAdded: diff.triggersAdded?.length || 0,
        triggersRemoved: diff.triggersRemoved?.length || 0,
        triggersModified: diff.triggersModified?.length || 0,
        functionsAdded: diff.functionsAdded?.length || 0,
        functionsRemoved: diff.functionsRemoved?.length || 0,
        functionsModified: diff.functionsModified?.length || 0,
        breakingChangeCount: breakingChanges.length
      },
      riskScore: {
        score: riskScore.score,
        label: riskScore.label,
        icon: riskScore.icon
      },
      breakingChanges,
      migration,
      rollback,
      totalMigrationLines: migration.split('\n').filter(l => l.trim()).length,
      teamUpsell: {
        text: 'Add drift alerts, a shared workspace, and Slack/Teams notifications with SchemaLens Team.',
        url: 'https://schemalens.tech/team-buy.html'
      },
      poweredBy: 'SchemaLens Free Diff API — https://schemalens.tech/api-guide.html'
    });
  } catch (err) {
    return res.status(500).json({ error: err.message || 'Internal server error' });
  }
};
