/**
 * SchemaLens Slack Webhook API
 * POST /api/slack
 *
 * Body:
 *   webhookUrl      string  required  Slack Incoming Webhook URL
 *   diff            object  required  Diff result from diffSchemas()
 *   migration       string  optional  Generated migration SQL
 *   breakingChanges array   optional  Detected breaking changes
 *   dialect         string  optional  postgres | mysql | sqlite | mssql | oracle
 *   tableLimit      number  optional  Number of tables in schema (for context)
 *
 * Response:
 *   { success: true, message: "Sent to Slack" }
 */

const rateLimitMap = new Map();
const RATE_LIMIT_WINDOW_MS = 60 * 1000;
const RATE_LIMIT_MAX = 10;

function isRateLimited(ip) {
  const now = Date.now();
  const entry = rateLimitMap.get(ip);
  if (!entry) {
    rateLimitMap.set(ip, { count: 1, resetAt: now + RATE_LIMIT_WINDOW_MS });
    return false;
  }
  if (now > entry.resetAt) {
    rateLimitMap.set(ip, { count: 1, resetAt: now + RATE_LIMIT_WINDOW_MS });
    return false;
  }
  entry.count++;
  if (entry.count > RATE_LIMIT_MAX) return true;
  return false;
}

setInterval(() => {
  const now = Date.now();
  for (const [ip, entry] of rateLimitMap) {
    if (now > entry.resetAt + RATE_LIMIT_WINDOW_MS) rateLimitMap.delete(ip);
  }
}, 5 * 60 * 1000);

function isValidSlackWebhook(url) {
  return typeof url === 'string' && /^https:\/\/hooks\.slack\.com\/services\//.test(url);
}

function truncate(str, len) {
  if (!str) return '';
  return str.length > len ? str.slice(0, len - 1) + '…' : str;
}

function formatSlackMessage(data) {
  const { diff, migration, breakingChanges, dialect } = data;
  const blocks = [];

  const added = diff.tablesAdded?.length || 0;
  const removed = diff.tablesRemoved?.length || 0;
  const modified = diff.tablesModified?.length || 0;
  const totalOld = diff.totalTablesOld || 0;
  const totalNew = diff.totalTablesNew || 0;

  let emoji = '🟡';
  if (breakingChanges && breakingChanges.length > 0) emoji = '🔴';
  else if (added === 0 && removed === 0 && modified === 0) emoji = '🟢';

  blocks.push({
    type: 'header',
    text: { type: 'plain_text', text: `${emoji} SchemaLens Diff Report`, emoji: true }
  });

  const summaryParts = [];
  if (added) summaryParts.push(`${added} table${added > 1 ? 's' : ''} added`);
  if (removed) summaryParts.push(`${removed} table${removed > 1 ? 's' : ''} removed`);
  if (modified) summaryParts.push(`${modified} table${modified > 1 ? 's' : ''} modified`);
  if (!summaryParts.length) summaryParts.push('No changes detected');

  blocks.push({
    type: 'section',
    fields: [
      { type: 'mrkdwn', text: `*Dialect:*\n${dialect || 'postgres'}` },
      { type: 'mrkdwn', text: `*Tables:*\n${totalOld} → ${totalNew}` },
      { type: 'mrkdwn', text: `*Changes:*\n${summaryParts.join(', ')}` },
      { type: 'mrkdwn', text: `*Breaking:*\n${breakingChanges?.length || 0} issue${(breakingChanges?.length || 0) !== 1 ? 's' : ''}` }
    ]
  });

  if (breakingChanges && breakingChanges.length > 0) {
    const dangerItems = breakingChanges.slice(0, 10).map(b => {
      const icon = b.severity === 'critical' ? '🔴' : '⚠️';
      return `${icon} ${truncate(b.details, 250)}`;
    });
    blocks.push({
      type: 'section',
      text: { type: 'mrkdwn', text: `*Breaking Changes:*\n${dangerItems.join('\n')}` }
    });
  }

  if (migration) {
    const sql = truncate(migration, 2800);
    blocks.push({
      type: 'section',
      text: { type: 'mrkdwn', text: `*Migration SQL:*\n\`\`\`sql\n${sql}\n\`\`\`` }
    });
  }

  blocks.push({
    type: 'context',
    elements: [
      { type: 'mrkdwn', text: `Generated by <https://schemalens.tech|SchemaLens> — compare SQL schemas in your browser.` }
    ]
  });

  return { blocks, text: `SchemaLens diff: ${summaryParts.join(', ')}` };
}

module.exports = async (req, res) => {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');

  if (req.method === 'OPTIONS') {
    return res.status(200).end();
  }

  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed. Use POST.' });
  }

  const clientIp = req.headers['x-forwarded-for']?.split(',')[0]?.trim() || req.socket?.remoteAddress || 'unknown';
  if (isRateLimited(clientIp)) {
    return res.status(429).json({ error: 'Rate limit exceeded. Maximum 10 Slack notifications per minute.' });
  }

  const { webhookUrl, diff, migration, breakingChanges, dialect } = req.body || {};

  if (!isValidSlackWebhook(webhookUrl)) {
    return res.status(400).json({ error: 'Invalid webhookUrl. Must be a Slack Incoming Webhook URL (https://hooks.slack.com/services/...).' });
  }

  if (!diff || typeof diff !== 'object') {
    return res.status(400).json({ error: 'diff object is required.' });
  }

  const payload = formatSlackMessage({ diff, migration, breakingChanges, dialect });

  try {
    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), 8000);

    const slackRes = await fetch(webhookUrl, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(payload),
      signal: controller.signal
    });

    clearTimeout(timeout);

    if (!slackRes.ok) {
      const text = await slackRes.text().catch(() => '');
      console.log(`SLACK_WEBHOOK_FAILED: ${slackRes.status} ${text}`);
      return res.status(502).json({ error: 'Slack returned an error. Check your webhook URL.' });
    }

    console.log(`SLACK_SENT: ${clientIp} | tables ${diff.totalTablesOld || 0}→${diff.totalTablesNew || 0}`);
    return res.status(200).json({ success: true, message: 'Sent to Slack successfully.' });
  } catch (err) {
    console.log(`SLACK_ERROR: ${err.message}`);
    return res.status(502).json({ error: 'Failed to send to Slack. Check your webhook URL and network.' });
  }
};
