#!/usr/bin/env node

/**
 * Changelog Generator
 * Converts Markdown files with YAML frontmatter to beautiful HTML changelogs
 */

const fs = require('fs');
const path = require('path');
const { marked } = require('marked');
const yamlFront = require('yaml-front-matter');

// Configuration
const CONFIG = {
  contentDir: process.env.CONTENT_DIR || './content',
  outputDir: process.env.OUTPUT_DIR || './dist',
  theme: process.env.THEME || 'minimal',
  siteName: process.env.SITE_NAME || 'Changelog',
  siteUrl: process.env.SITE_URL || '',
  enableAnalytics: process.env.ENABLE_ANALYTICS === 'true',
};

// Parse command line args
const args = process.argv.slice(2);
const watchMode = args.includes('--watch');

/**
 * Load and parse all markdown files from content directory
 */
function loadEntries() {
  const contentPath = path.resolve(CONFIG.contentDir);
  
  if (!fs.existsSync(contentPath)) {
    console.error(`❌ Content directory not found: ${contentPath}`);
    process.exit(1);
  }

  const files = fs.readdirSync(contentPath)
    .filter(f => f.endsWith('.md'))
    .sort((a, b) => b.localeCompare(a)); // Sort by filename (date) descending

  const entries = files.map(file => {
    const filePath = path.join(contentPath, file);
    const content = fs.readFileSync(filePath, 'utf-8');
    const parsed = yamlFront.loadFront(content);
    
    // Extract date from filename (YYYY-MM-DD-*.md) or frontmatter
    const dateMatch = file.match(/(\d{4}-\d{2}-\d{2})/);
    const fileDate = dateMatch ? dateMatch[1] : null;
    
    // Handle YAML date objects vs string dates
    let entryDate = parsed.date || fileDate;
    if (entryDate instanceof Date) {
      entryDate = entryDate.toISOString().split('T')[0];
    }
    
    return {
      title: parsed.title || 'Untitled',
      date: entryDate,
      category: parsed.category || 'Update',
      tags: parsed.tags || [],
      author: parsed.author || '',
      image: parsed.image || '',
      slug: file.replace('.md', ''),
      content: marked(parsed.__content || ''),
      rawContent: parsed.__content || '',
      githubRelease: parsed.github_release || '',
      prerelease: parsed.prerelease || false,
      autoGenerated: parsed.auto_generated || false,
    };
  });

  // Filter out future-dated entries
  const now = new Date().toISOString().split('T')[0];
  return entries.filter(e => !e.date || e.date <= now);
}

/**
 * Fetch GitHub releases and convert to changelog entries
 */
async function loadEntriesFromGitHubReleases(repo, options = {}) {
  const { includePrereleases = true, limit = 50 } = options;
  
  console.log(`   Fetching releases from GitHub: ${repo}`);
  
  // GitHub API endpoint
  const apiUrl = `https://api.github.com/repos/${repo}/releases?per_page=${limit}`;
  
  try {
    // Use native https for no dependencies
    const https = require('https');
    
    const releases = await new Promise((resolve, reject) => {
      const req = https.get(apiUrl, {
        headers: {
          'User-Agent': 'Changelog.page Generator',
          'Accept': 'application/vnd.github.v3+json',
        },
        timeout: 10000,
      }, (res) => {
        let data = '';
        res.on('data', chunk => data += chunk);
        res.on('end', () => {
          if (res.statusCode === 200) {
            try {
              resolve(JSON.parse(data));
            } catch (e) {
              reject(new Error('Failed to parse GitHub API response'));
            }
          } else if (res.statusCode === 404) {
            reject(new Error(`Repository not found: ${repo}`));
          } else if (res.statusCode === 403) {
            reject(new Error('GitHub API rate limit exceeded. Try again later or use GITHUB_TOKEN.'));
          } else {
            reject(new Error(`GitHub API error: ${res.statusCode}`));
          }
        });
      });
      
      req.on('error', reject);
      req.on('timeout', () => {
        req.destroy();
        reject(new Error('Request timeout'));
      });
    });
    
    // Convert releases to changelog entries
    const entries = releases
      .filter(release => includePrereleases || !release.prerelease)
      .map(release => {
        const date = new Date(release.published_at || release.created_at);
        const dateStr = date.toISOString().split('T')[0];
        const tag = release.tag_name;
        
        // Determine category
        let category = 'Release';
        if (release.prerelease) {
          category = 'Prerelease';
        } else {
          const versionMatch = tag.match(/v?(\d+)\.(\d+)\.(\d+)/);
          if (versionMatch) {
            const [, major, minor, patch] = versionMatch;
            if (patch === '0' && minor === '0' && major !== '0') {
              category = 'Major Release';
            } else if (patch === '0') {
              category = 'Feature Release';
            } else {
              category = 'Patch Release';
            }
          }
        }
        
        // Extract tags from body
        const tags = [];
        if (release.body) {
          const tagMatches = release.body.match(/#(\w+)/g);
          if (tagMatches) {
            tagMatches.forEach(t => tags.push(t.slice(1)));
          }
        }
        if (tags.length === 0) {
          tags.push('release');
        }
        
        // Build content with link back to GitHub
        let content = release.body || '';
        // Remove tag references from content
        content = content.replace(/#\w+/g, '').trim();
        // Add GitHub link
        content += `\n\n---\n\n[View release on GitHub](${release.html_url})`;
        
        return {
          title: release.name || `Release ${tag}`,
          date: dateStr,
          category,
          tags,
          author: release.author?.login || '',
          image: '',
          slug: `release-${tag.replace(/\./g, '-').replace(/[^a-zA-Z0-9-_]/g, '')}`,
          content: marked(content),
          rawContent: content,
          githubRelease: tag,
          prerelease: release.prerelease,
          autoGenerated: false,
        };
      });
    
    console.log(`   ✓ Fetched ${entries.length} releases`);
    return entries;
    
  } catch (error) {
    console.error(`   ❌ ${error.message}`);
    return [];
  }
}

/**
 * Load theme template
 */
function loadTheme(themeName) {
  const themePath = path.resolve(__dirname, '../themes', themeName, 'template.html');
  
  if (!fs.existsSync(themePath)) {
    console.error(`❌ Theme not found: ${themeName}`);
    console.log(`Available themes: ${getAvailableThemes().join(', ')}`);
    process.exit(1);
  }
  
  return fs.readFileSync(themePath, 'utf-8');
}

/**
 * Get list of available themes
 */
function getAvailableThemes() {
  const themesPath = path.resolve(__dirname, '../themes');
  if (!fs.existsSync(themesPath)) return [];
  return fs.readdirSync(themesPath).filter(f => {
    return fs.statSync(path.join(themesPath, f)).isDirectory();
  });
}

/**
 * Copy theme assets to output directory
 */
function copyThemeAssets(themeName) {
  const sourceDir = path.resolve(__dirname, '../themes', themeName);
  const destDir = path.resolve(CONFIG.outputDir);
  
  // Copy CSS, JS, images
  ['css', 'js', 'images'].forEach(dir => {
    const source = path.join(sourceDir, dir);
    const dest = path.join(destDir, dir);
    
    if (fs.existsSync(source)) {
      if (!fs.existsSync(dest)) {
        fs.mkdirSync(dest, { recursive: true });
      }
      copyDirectory(source, dest);
    }
  });
  
  // Copy shared analytics assets if analytics is enabled
  if (CONFIG.enableAnalytics) {
    copyAnalyticsAssets(destDir);
  }
}

/**
 * Copy analytics assets to output directory
 */
function copyAnalyticsAssets(destDir) {
  const sharedDir = path.resolve(__dirname, '../themes/shared');
  
  // Copy analytics.js
  const analyticsSource = path.join(sharedDir, 'js', 'analytics.js');
  const analyticsDest = path.join(destDir, 'js', 'analytics.js');
  if (fs.existsSync(analyticsSource)) {
    if (!fs.existsSync(path.dirname(analyticsDest))) {
      fs.mkdirSync(path.dirname(analyticsDest), { recursive: true });
    }
    fs.copyFileSync(analyticsSource, analyticsDest);
    console.log('   ✓ Analytics tracking enabled');
  }
  
  // Copy analytics-dashboard.html
  const dashboardSource = path.join(sharedDir, 'analytics-dashboard.html');
  const dashboardDest = path.join(destDir, 'analytics.html');
  if (fs.existsSync(dashboardSource)) {
    let dashboardTemplate = fs.readFileSync(dashboardSource, 'utf-8');
    dashboardTemplate = dashboardTemplate.replace(/\{\{site_name\}\}/g, CONFIG.siteName);
    fs.writeFileSync(dashboardDest, dashboardTemplate);
    console.log('   ✓ Analytics dashboard created');
  }
}

/**
 * Recursively copy directory
 */
function copyDirectory(source, dest) {
  const entries = fs.readdirSync(source, { withFileTypes: true });
  
  for (const entry of entries) {
    const sourcePath = path.join(source, entry.name);
    const destPath = path.join(dest, entry.name);
    
    if (entry.isDirectory()) {
      if (!fs.existsSync(destPath)) {
        fs.mkdirSync(destPath, { recursive: true });
      }
      copyDirectory(sourcePath, destPath);
    } else {
      fs.copyFileSync(sourcePath, destPath);
    }
  }
}

/**
 * Generate RSS feed
 */
function generateRSS(entries) {
  const lastBuildDate = new Date().toUTCString();
  const items = entries.slice(0, 20).map(entry => `
    <item>
      <title>${escapeXml(entry.title)}</title>
      <link>${CONFIG.siteUrl}/${entry.slug}</link>
      <guid>${CONFIG.siteUrl}/${entry.slug}</guid>
      <pubDate>${new Date(entry.date).toUTCString()}</pubDate>
      <description>${escapeXml(entry.rawContent.substring(0, 500))}...</description>
    </item>
  `).join('');

  return `<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>${CONFIG.siteName}</title>
    <link>${CONFIG.siteUrl}</link>
    <description>Product updates and changelog</description>
    <lastBuildDate>${lastBuildDate}</lastBuildDate>
    <atom:link href="${CONFIG.siteUrl}/rss.xml" rel="self" type="application/rss+xml"/>
    ${items}
  </channel>
</rss>`;
}

/**
 * Generate JSON Feed
 */
function generateJSONFeed(entries) {
  return JSON.stringify({
    version: 'https://jsonfeed.org/version/1.1',
    title: CONFIG.siteName,
    home_page_url: CONFIG.siteUrl,
    feed_url: `${CONFIG.siteUrl}/feed.json`,
    items: entries.slice(0, 20).map(entry => ({
      id: entry.slug,
      url: `${CONFIG.siteUrl}/${entry.slug}`,
      title: entry.title,
      content_html: entry.content,
      date_published: entry.date,
      tags: entry.tags,
    })),
  }, null, 2);
}

/**
 * Escape XML special characters
 */
function escapeXml(str) {
  if (!str) return '';
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

/**
 * Build the changelog site
 */
async function build() {
  console.log('🔨 Building changelog...');
  console.log(`   Theme: ${CONFIG.theme}`);
  console.log(`   Content: ${CONFIG.contentDir}`);
  console.log(`   Output: ${CONFIG.outputDir}`);

  // Load data
  let entries = loadEntries();
  
  // If GITHUB_REPO is set, also fetch releases from GitHub
  if (process.env.GITHUB_REPO) {
    const githubEntries = await loadEntriesFromGitHubReleases(process.env.GITHUB_REPO, {
      includePrereleases: process.env.GITHUB_INCLUDE_PRERELEASES !== 'false',
      limit: parseInt(process.env.GITHUB_RELEASES_LIMIT || '50'),
    });
    
    // Merge entries, avoiding duplicates by githubRelease tag
    const existingTags = new Set(entries.filter(e => e.githubRelease).map(e => e.githubRelease));
    const newGithubEntries = githubEntries.filter(e => !existingTags.has(e.githubRelease));
    
    if (newGithubEntries.length > 0) {
      entries = [...entries, ...newGithubEntries];
      // Re-sort by date descending
      entries.sort((a, b) => {
        if (!a.date) return 1;
        if (!b.date) return -1;
        return b.date.localeCompare(a.date);
      });
    }
  }
  
  console.log(`   Found ${entries.length} entries`);

  // Load theme
  const template = loadTheme(CONFIG.theme);

  // Ensure output directory exists
  if (!fs.existsSync(CONFIG.outputDir)) {
    fs.mkdirSync(CONFIG.outputDir, { recursive: true });
  }

  // Copy theme assets
  copyThemeAssets(CONFIG.theme);

  // Generate index page
  let indexHtml = template
    .replace(/{{site_name}}/g, CONFIG.siteName)
    .replace(/{{site_description}}/g, 'Product updates and changelog')
    .replace('{{entries}}', generateEntriesHTML(entries))
    .replace('{{feed_meta}}', generateFeedMeta());
  
  // Inject analytics if enabled
  if (CONFIG.enableAnalytics) {
    indexHtml = injectAnalytics(indexHtml);
  }

  fs.writeFileSync(path.join(CONFIG.outputDir, 'index.html'), indexHtml);

  // Generate RSS feed
  fs.writeFileSync(path.join(CONFIG.outputDir, 'rss.xml'), generateRSS(entries));

  // Generate JSON feed
  fs.writeFileSync(path.join(CONFIG.outputDir, 'feed.json'), generateJSONFeed(entries));

  // Generate individual entry pages (optional, for SEO)
  entries.forEach(entry => {
    let entryHtml = template
      .replace(/{{site_name}}/g, `${entry.title} | ${CONFIG.siteName}`)
      .replace(/{{site_description}}/g, entry.rawContent.substring(0, 160))
      .replace('{{entries}}', generateSingleEntryHTML(entry))
      .replace('{{feed_meta}}', generateFeedMeta());
    
    // Inject analytics if enabled
    if (CONFIG.enableAnalytics) {
      entryHtml = injectAnalytics(entryHtml);
    }
    
    fs.writeFileSync(path.join(CONFIG.outputDir, `${entry.slug}.html`), entryHtml);
  });

  console.log('✅ Build complete!');
  console.log(`   Output: ${path.resolve(CONFIG.outputDir)}`);
  
  if (CONFIG.enableAnalytics) {
    console.log('📊 Analytics enabled - view dashboard at: /analytics.html');
  }
}

/**
 * Inject analytics tracking code into HTML
 */
function injectAnalytics(html) {
  // Add analytics meta tag before </head>
  html = html.replace(
    '</head>',
    '  <meta name="changelog-analytics" content="true">\n  <script src="js/analytics.js" defer></script>\n</head>'
  );
  
  // Add analytics dashboard link to footer if exists
  if (html.includes('</footer>')) {
    html = html.replace(
      '</footer>',
      '    <div class="analytics-link" style="text-align: center; margin-top: 2rem; padding-top: 2rem; border-top: 1px solid #1e293b;">\n      <a href="analytics.html" style="color: #64748b; font-size: 0.875rem; text-decoration: none;">📊 View Analytics</a>\n    </div>\n  </footer>'
    );
  }
  
  return html;
}

/**
 * Generate HTML for all entries
 */
function generateEntriesHTML(entries) {
  return entries.map(entry => {
    // Build badges
    const badges = [];
    if (entry.prerelease) {
      badges.push('<span class="entry-badge entry-badge--prerelease">Prerelease</span>');
    }
    if (entry.githubRelease) {
      badges.push(`<span class="entry-badge entry-badge--github" title="GitHub Release ${entry.githubRelease}">⬢ ${entry.githubRelease}</span>`);
    }
    if (entry.autoGenerated) {
      badges.push('<span class="entry-badge entry-badge--auto" title="Auto-generated from commits">🤖 Auto</span>');
    }
    
    return `
    <article class="entry" data-category="${entry.category.toLowerCase().replace(/\s+/g, '-')}"
             ${entry.githubRelease ? `data-release="${entry.githubRelease}"` : ''}>
      <header class="entry-header">
        <div class="entry-meta">
          <span class="entry-category">${entry.category}</span>
          <time class="entry-date" datetime="${entry.date}">${formatDate(entry.date)}</time>
          ${badges.length ? `<span class="entry-badges">${badges.join('')}</span>` : ''}
        </div>
        <h2 class="entry-title">
          <a href="${entry.slug}.html">${entry.title}</a>
        </h2>
      </header>
      <div class="entry-content">
        ${entry.content}
      </div>
      ${entry.tags.length ? `
      <footer class="entry-footer">
        ${entry.tags.map(tag => `<span class="entry-tag">#${tag}</span>`).join(' ')}
      </footer>
      ` : ''}
    </article>
  `}).join('\n');
}

/**
 * Generate HTML for single entry
 */
function generateSingleEntryHTML(entry) {
  return `
    <article class="entry entry--single" data-category="${entry.category.toLowerCase()}">
      <header class="entry-header">
        <div class="entry-meta">
          <span class="entry-category">${entry.category}</span>
          <time class="entry-date" datetime="${entry.date}">${formatDate(entry.date)}</time>
        </div>
        <h1 class="entry-title">${entry.title}</h1>
      </header>
      <div class="entry-content">
        ${entry.content}
      </div>
      ${entry.tags.length ? `
      <footer class="entry-footer">
        ${entry.tags.map(tag => `<span class="entry-tag">#${tag}</span>`).join(' ')}
      </footer>
      ` : ''}
      <nav class="entry-nav">
        <a href="index.html" class="entry-nav__back">← Back to changelog</a>
      </nav>
    </article>
  `;
}

/**
 * Generate feed auto-discovery meta tags
 */
function generateFeedMeta() {
  return `
    <link rel="alternate" type="application/rss+xml" title="${CONFIG.siteName} RSS" href="${CONFIG.siteUrl}/rss.xml">
    <link rel="alternate" type="application/json" title="${CONFIG.siteName} JSON Feed" href="${CONFIG.siteUrl}/feed.json">
  `;
}

/**
 * Format date for display
 */
function formatDate(dateStr) {
  if (!dateStr) return '';
  const date = new Date(dateStr);
  return date.toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
}

// Run build
build().catch(err => {
  console.error('❌ Build failed:', err.message);
  process.exit(1);
});

// Watch mode
if (watchMode) {
  console.log('👀 Watching for changes...');
  fs.watch(CONFIG.contentDir, { recursive: true }, () => {
    console.log('\n📝 Changes detected, rebuilding...');
    build().catch(err => {
      console.error('❌ Build failed:', err.message);
    });
  });
}
